baseURL = "https://ibzsy.github.io/"
title = "ibzsy"
theme = ["etch", "hugo-shortcode-gallery"]
languageCode = "en-UK"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "ibzsy's blog"
  copyright = "copyright © 2025 Ibrahim"
  dark = "auto"
  highlight = true


[taxonomies]
  tag = nan
  category = nan
